describe('[square]', function () {
  "use strict";

  var Square = require('../lib/square');

  it('it is so awesome');

  describe('@construction', function () {
    it('should construct without any errors');

    it('should not override private properties');

    it('should silence the logger when stdout is changed');

    it('should set the correct env based on NODE_ENV');

    it('should find the correct $HOME directory');
  });

  describe('#has', function () {
    it('should find duplicate plugins');
  });

  describe('#use', function () {
    it('should only accept functions');

    it('should not add duplicate plugins');
  });

  describe('#plugin', function () {
    it('should require the given plugin by name');

    it('should proxy the configuration to the plugin');

    it('should log an critical error when it fails');
  });

  describe('#configure', function () {
    it('should call the function if no evn variable is given');

    it('should not execute the function if the env doesnt match');

    it('should execute the function on evn match');
  });

  describe('#forEach', function () {
    it('should iterate over all plugins');

    it('should catch errors generated by the plugins');

    it('should handle plugins that doesnst return content');
  });
});
